import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import { robotoSlab } from "./Fonts";
import Footer from "./components/footer/Footer";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={robotoSlab.variable}>
      <body
        className= 'antialiased'
      >
        {/* <Navbar /> */}
        {children}
        <ToastContainer position="top-center" autoClose={3000} />
        <Footer />
      </body>
    </html>
  );
}
